# Generated by Django 2.2.6 on 2019-11-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='specialization',
            field=models.CharField(default='Не указано', max_length=200),
        ),
        migrations.AlterField(
            model_name='background',
            name='faculty',
            field=models.CharField(max_length=300),
        ),
    ]
