# Generated by Django 2.2.6 on 2019-11-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0002_auto_20191104_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='level',
            field=models.CharField(default='Не указано', max_length=150),
        ),
    ]
