# Generated by Django 2.2.6 on 2019-11-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Backgrounds',
            new_name='Background',
        ),
    ]
