# Generated by Django 2.2.6 on 2019-11-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=300)),
                ('responsibilities', models.CharField(max_length=300)),
            ],
        ),
    ]
