# Generated by Django 2.2.6 on 2019-11-09 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='time_end',
            field=models.DateField(default=datetime.date(2019, 11, 10)),
        ),
        migrations.AddField(
            model_name='experience',
            name='time_start',
            field=models.DateField(default=datetime.date(2019, 11, 10)),
        ),
    ]
