# Generated by Django 2.2.6 on 2019-11-09 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20191110_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='time_end',
            field=models.DateField(blank=True, default=datetime.date(2019, 11, 10), null=True),
        ),
    ]
