# Generated by Django 2.2.6 on 2019-11-16 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20191110_0108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='background',
            options={'ordering': ['year_start']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['time_start']},
        ),
        migrations.AlterField(
            model_name='experience',
            name='time_end',
            field=models.DateField(blank=True, default=datetime.date(2019, 11, 16), null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='time_start',
            field=models.DateField(default=datetime.date(2019, 11, 16)),
        ),
    ]
