# Generated by Django 2.2.6 on 2019-11-23 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_auto_20191116_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='time_end',
            field=models.DateField(blank=True, default=datetime.date(2019, 11, 23), null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='time_start',
            field=models.DateField(default=datetime.date(2019, 11, 23)),
        ),
    ]
